# Generated by Django 4.1.7 on 2023-03-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charges", "0003_document_packageofreceipts_documents_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packageofreceipts",
            options={
                "verbose_name": "Пакет квитанций",
                "verbose_name_plural": "Пакеты квитанций",
            },
        ),
        migrations.AlterModelOptions(
            name="packageofservices",
            options={
                "verbose_name": "Пакет услуг",
                "verbose_name_plural": "Пакеты услуг",
            },
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name": "Тип", "verbose_name_plural": "Тип"},
        ),
    ]
