# Generated by Django 4.1.7 on 2023-08-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charges", "0004_alter_packageofreceipts_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentOfPackageOfReceipts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="", verbose_name="Файл")),
            ],
        ),
        migrations.CreateModel(
            name="DocumentOfPackageOfServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="", verbose_name="Файл")),
            ],
        ),
        migrations.RemoveField(
            model_name="packageofreceipts",
            name="documents",
        ),
        migrations.RemoveField(
            model_name="packageofservices",
            name="documents",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.AddField(
            model_name="documentofpackageofservices",
            name="package_of_services",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="charges.packageofservices",
            ),
        ),
        migrations.AddField(
            model_name="documentofpackageofreceipts",
            name="package_of_receipts",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="charges.packageofreceipts",
            ),
        ),
    ]
