# Generated by Django 5.0.4 on 2024-04-09 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0009_remove_packageofreceipts_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentofpackageofreceipts',
            options={'verbose_name': 'Прикрепленные файлы к пакету квитанций', 'verbose_name_plural': 'Прикрепленные файлы к пакету квитанций'},
        ),
        migrations.AlterModelOptions(
            name='documentofpackageofservices',
            options={'verbose_name': 'Прикрепленные файлы к пакету услуг', 'verbose_name_plural': 'Прикрепленные файлы к пакету услуг'},
        ),
        migrations.AlterModelOptions(
            name='paymentofpackageofreceipts',
            options={'verbose_name': 'Чеки к пакету квитанций', 'verbose_name_plural': 'Чеки к пакету квитанций'},
        ),
        migrations.AlterModelOptions(
            name='paymentofpackageofservices',
            options={'verbose_name': 'Чеки к пакету услуг', 'verbose_name_plural': 'Чеки к пакету услуг'},
        ),
        migrations.AlterField(
            model_name='packageofreceipts',
            name='description',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='packageofreceipts',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='packageofreceipts',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'Оплачено'), ('Требуется оплата', 'Требуется оплата')], max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='packageofreceipts',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charges.typeofreceipts', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='packageofservices',
            name='description',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='packageofservices',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='packageofservices',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'Оплачено'), ('Требуется оплата', 'Требуется оплата')], max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='packageofservices',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charges.typeofservices', verbose_name='Тип'),
        ),
    ]
