# Generated by Django 4.1.7 on 2023-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="documents",
            field=models.ManyToManyField(to="dictionary.document"),
        ),
    ]
