# Generated by Django 4.1.7 on 2023-03-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_organization_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="documents",
            field=models.ManyToManyField(default=None, to="dictionary.document"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="tax_system",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="dictionary.taxsystem",
                verbose_name="Система налогообложения",
            ),
        ),
    ]
