# Generated by Django 4.1.7 on 2023-03-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_alter_organization_documents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="tax_system",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="dictionary.taxsystem",
                verbose_name="Система налогообложения",
            ),
        ),
    ]
