# Generated by Django 4.1.7 on 2023-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0005_alter_organization_tax_system"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="sur_name",
        ),
        migrations.AddField(
            model_name="organization",
            name="middle_name",
            field=models.CharField(default="", max_length=255, verbose_name="Отчество"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="documents",
            field=models.ManyToManyField(
                default=None, to="dictionary.document", verbose_name="Документы"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
