# Generated by Django 4.1.7 on 2023-03-26 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0006_remove_organization_sur_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.AlterModelOptions(
            name="taxsystem",
            options={
                "verbose_name": "Система налогообложения",
                "verbose_name_plural": "Системы налогообложения",
            },
        ),
        migrations.RemoveField(
            model_name="organization",
            name="documents",
        ),
        migrations.AddField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организация",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                blank=True, choices=[("ИП", "ИП"), ("ООО", "ООО")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone",
            field=models.CharField(blank=True, max_length=255, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="tax_system",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="dictionary.taxsystem",
                verbose_name="Система налогообложения",
            ),
        ),
    ]
