# Generated by Django 4.2.1 on 2023-06-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_alter_organization_tax_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(choices=[('Копия ИНН', 'Копия ИНН'), ('Копия ОГРНИП', 'Копия ОГРНИП')], max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('ИП', 'ИП'), ('ООО', 'ООО')], max_length=10, verbose_name='Организационно-правовая форма'),
        ),
    ]
